version: "2"

services:

  backend:
    build:
      context: .
      dockerfile: './Dockerfile'
    volumes:
      - ./storage:/res/storage
    restart: always
    ports:
      - "3000"
    environment:
      - LETSENCRYPT_EMAIL=mail@jinhyung.kim
      - LETSENCRYPT_HOST=sns.jinhyung.kim
      - VIRTUAL_HOST=sns.jinhyung.kim
      - VIRTUAL_PORT=3000


networks:
  default:
    external:
      name: reverse-proxy